export const SET_FILE_INPUT = 'SET_FILE_INPUT'
export const SEND_AVATAR_IMAGE = 'SEND_AVATAR_IMAGE'
export const UPLOAD_CURRENT_PROFILE_AVATAR_URL = 'UPLOAD_PROFILE_AVATAR_URL'
export const SET_CURRENT_PROFILE_AVATAR_URL = 'SET_CURRENT_PROFILE_AVATAR_URL'
